store/site/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('store.site.views',
    (r'^$', 'index'), )

store/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^', include('store.site.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

store/models.py
from django.db import models

BEVERAGE_TYPES = (
    ('B', 'Beer'),
    ('W', 'Wine'),
    ('O', 'Other'),
)
    

class Product(models.Model):
    """Basic Product Definition."""

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True,
                                   null=True)
    slug = models.SlugField(max_length=120,
                            db_index=True,
                            unique=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=2)
    regular_price = models.DecimalField(max_digits=10,
                                decimal_places=2,
                                blank=True,
                                null=True)
    image = models.ImageField(upload_to='products')
    disabled = models.BooleanField()

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.name


class Beverage(Product):
    """Built to abstract Beer and Wine similarities."""
    
    SIZE_UNIT_TYPES = (
        ('OZ', 'OZ'),
        ('P', 'Pack'),
    )

    CONTAINER_TYPES = (
        ('B', 'BTL'),
        ('C', 'CAN'),
    )

    alcohol = models.DecimalField(max_digits=5,
                                  decimal_places=2,
                                  blank=True,
                                  null=True)
    company = models.ForeignKey('Company')
    # country : TODO
    size_unit = models.CharField(max_length=3, 
                                 choices=SIZE_UNIT_TYPES) # OZ , mm, Pack
    size_value = models.CharField(max_length=10) # 22, 4, 6, 750
    container = models.CharField(max_length=2,
                                 choices=CONTAINER_TYPES) # BTL, CAN, Box etc. 
    abv = models.DecimalField(max_digits=4,
                              decimal_places=2,
                              blank=True,
                              null=True)
    

class BeverageStyle(models.Model):
    """Beverage style.

    eg: Ale / IPA / Lager / Cabernet etc. 
    """
    name = models.CharField(max_length=150)
    beverage_type = models.CharField(max_length=2,
                                     choices=BEVERAGE_TYPES)

    def __unicode__(self):
        return self.name


class WineStyle(BeverageStyle):

    class Meta:
        proxy = True


class BeerStyle(BeverageStyle):

    class Meta:
        proxy = True


class Beer(Beverage):
    """Beer Definition."""
    ibu = models.IntegerField(blank=True, null=True)
    """
    Bitterness shown in International Bittering Units, where:
        - Low bitterness 0 - 20
        - Moderate bitterness 21 - 30
        - Noticeable bitterness 31 and over
    """
    style = models.ForeignKey('BeerStyle')# Ale / IPA / Lager / Cabernet 


class Wine(Beverage):
    """Wine Definition."""
    # region = 
    # vintage =
    style = models.ForeignKey('WineStyle') # 


class Company(models.Model):
    """Company name for Beverage."""

    beverage_type = models.CharField(max_length=2,
                                     choices=BEVERAGE_TYPES)
    name = models.CharField(max_length=255)
    
    def __unicode__(self):
        return self.name

store/site/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext, loader

from store.models import Beer
from store.models import BeerStyle

def index(request):
    """Home page"""
    template = loader.get_template('index.html')
    beers = Beer.objects.all()[:10]
    context = RequestContext(request, {
        'styles': BeerStyle.objects.all(),
        'beers': beers,
        })
    
    return HttpResponse(template.render(context))

store/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
		"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=UTF-8" />
        <title>SF Beer Club </title>
        <link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}css/site.css" />
    </head>
    <body>
        <div id="main_container">
            <div id="header">
                <div id="menu">
                    Home | About | Cart
                </div>
            </div>
            <div id="left_search">
                {% block browse %}{% endblock %}
                <h4>Style</h4>
                <ul>
                {% for style in styles %}
                    <li>{{ style }}</li>
                {% endfor %}
                </ul>
                <h4>Price:</h4>
            </div>
            <div id="middle_container">
                {% block middle %}{% endblock %}
            </div>
            <div id="right_container">
                {% block right %}{% endblock %} right
            </div>
        </div>
    </body>
</html>

store/templates/index.html
{% extends 'base.html' %}
{% block middle %}
{% for beer in beers %}
<div class="beer_list_item">
    <p><a href="#">{{ beer.name }}</a></p>
    <p>{{ beer.description }}</p>
    <p>{{ beer.size_value }} {{ beer.get_size_unit_display }} - 
                             {{ beer.get_container_display }}</p>
</div>
{% endfor %}
{% endblock %}